import type { WordPair } from './types';

export const WORD_PAIRS: WordPair[] = [
  // Minuman
  { civilian: 'Kopi', undercover: 'Teh', category: 'Minuman' },

  // Makanan
  { civilian: 'Rendang', undercover: 'Gulai', category: 'Makanan' },
  { civilian: 'Sate', undercover: 'Tongseng', category: 'Makanan' },
  { civilian: 'Apel', undercover: 'Pir', category: 'Makanan' },
  { civilian: 'Jeruk', undercover: 'Lemon', category: 'Makanan' },
  { civilian: 'Gado-Gado', undercover: 'Pecel', category: 'Makanan' },
  { civilian: 'Kerupuk', undercover: 'Rempeyek', category: 'Makanan' },
  { civilian: 'Donat', undercover: 'Bolu', category: 'Makanan' },
  { civilian: 'Rawon', undercover: 'Semur', category: 'Makanan' },
  { civilian: 'Batagor', undercover: 'Siomay', category: 'Makanan' },
  { civilian: 'Semangka', undercover: 'Melon', category: 'Makanan' },
  { civilian: 'Mangga', undercover: 'Pepaya', category: 'Makanan' },
  { civilian: 'Rambutan', undercover: 'Kelengkeng', category: 'Makanan' },
  { civilian: 'Durian', undercover: 'Nangka', category: 'Makanan' },

  // Hewan
  { civilian: 'Kucing', undercover: 'Anjing', category: 'Hewan' },
  { civilian: 'Ayam', undercover: 'Bebek', category: 'Hewan' },
  { civilian: 'Harimau', undercover: 'Singa', category: 'Hewan' },
  { civilian: 'Kambing', undercover: 'Domba', category: 'Hewan' },
  { civilian: 'Sapi', undercover: 'Kerbau', category: 'Hewan' },
  { civilian: 'Ular', undercover: 'Belut', category: 'Hewan' },
  { civilian: 'Kelinci', undercover: 'Marmut', category: 'Hewan' },
  { civilian: 'Gajah', undercover: 'Badak', category: 'Hewan' },
  { civilian: 'Buaya', undercover: 'Komodo', category: 'Hewan' },
  { civilian: 'Kupu-Kupu', undercover: 'Ngengat', category: 'Hewan' },
  { civilian: 'Semut', undercover: 'Rayap', category: 'Hewan' },
  { civilian: 'Udang', undercover: 'Kepiting', category: 'Hewan' },
  { civilian: 'Merpati', undercover: 'Elang', category: 'Hewan' },
  { civilian: 'Monyet', undercover: 'Orangutan', category: 'Hewan' },
  { civilian: 'Kura-Kura', undercover: 'Penyu', category: 'Hewan' },
  { civilian: 'Katak', undercover: 'Kodok', category: 'Hewan' },

  // Tempat
  { civilian: 'Pantai', undercover: 'Danau', category: 'Tempat' },
  { civilian: 'Gunung', undercover: 'Bukit', category: 'Tempat' },
  { civilian: 'Sekolah', undercover: 'Kampus', category: 'Tempat' },
  { civilian: 'Pasar', undercover: 'Mall', category: 'Tempat' },
  { civilian: 'Bandara', undercover: 'Stasiun', category: 'Tempat' },
  { civilian: 'Warung', undercover: 'Restoran', category: 'Tempat' },
  { civilian: 'Masjid', undercover: 'Musala', category: 'Tempat' },
  { civilian: 'Sawah', undercover: 'Ladang', category: 'Tempat' },
  { civilian: 'Hutan', undercover: 'Kebun', category: 'Tempat' },
  { civilian: 'Bioskop', undercover: 'Teater', category: 'Tempat' },
  { civilian: 'Apartemen', undercover: 'Kos-Kosan', category: 'Tempat' },

  // Profesi
  { civilian: 'Dokter', undercover: 'Perawat', category: 'Profesi' },
  { civilian: 'Polisi', undercover: 'Tentara', category: 'Profesi' },
  { civilian: 'Guru', undercover: 'Dosen', category: 'Profesi' },
  { civilian: 'Koki', undercover: 'Baker', category: 'Profesi' },
  { civilian: 'Petani', undercover: 'Nelayan', category: 'Profesi' },
  { civilian: 'Pilot', undercover: 'Masinis', category: 'Profesi' },
  { civilian: 'Wartawan', undercover: 'Fotografer', category: 'Profesi' },
  { civilian: 'Pengacara', undercover: 'Hakim', category: 'Profesi' },
  { civilian: 'Penyanyi', undercover: 'Musisi', category: 'Profesi' },
  { civilian: 'Kasir', undercover: 'Pelayan', category: 'Profesi' },

  // Objek
  { civilian: 'Sepeda', undercover: 'Motor', category: 'Objek' },
  { civilian: 'Bus', undercover: 'Kereta', category: 'Objek' },
  { civilian: 'Laptop', undercover: 'Komputer', category: 'Objek' },
  { civilian: 'Handphone', undercover: 'Tablet', category: 'Objek' },
  { civilian: 'Gitar', undercover: 'Ukulele', category: 'Objek' },
  { civilian: 'Sepatu', undercover: 'Sandal', category: 'Objek' },
  { civilian: 'Dompet', undercover: 'Tas', category: 'Objek' },
  { civilian: 'Pensil', undercover: 'Pulpen', category: 'Objek' },
  { civilian: 'Kulkas', undercover: 'Freezer', category: 'Objek' },
  { civilian: 'Sapu', undercover: 'Pel', category: 'Objek' },
  { civilian: 'Bantal', undercover: 'Guling', category: 'Objek' },
  { civilian: 'Selimut', undercover: 'Sarung', category: 'Objek' },
  { civilian: 'Cangkir', undercover: 'Gelas', category: 'Objek' },
  { civilian: 'Piring', undercover: 'Mangkuk', category: 'Objek' },
  { civilian: 'Sendok', undercover: 'Garpu', category: 'Objek' },
  { civilian: 'Ember', undercover: 'Baskom', category: 'Objek' },
  { civilian: 'Koper', undercover: 'Ransel', category: 'Objek' },
  { civilian: 'Kalkulator', undercover: 'Sempoa', category: 'Objek' },
  { civilian: 'Radio', undercover: 'Televisi', category: 'Objek' },

  // Olahraga
  { civilian: 'Basket', undercover: 'Voli', category: 'Olahraga' },
  { civilian: 'Renang', undercover: 'Selam', category: 'Olahraga' },
  { civilian: 'Panahan', undercover: 'Menembak', category: 'Olahraga' },

  // Umum
  { civilian: 'Hujan', undercover: 'Salju', category: 'Umum' },
  { civilian: 'Matahari', undercover: 'Bulan', category: 'Umum' },
  { civilian: 'Pagi', undercover: 'Sore', category: 'Umum' },
  { civilian: 'Pelangi', undercover: 'Aurora', category: 'Umum' },
  { civilian: 'Api', undercover: 'Petir', category: 'Umum' },
  { civilian: 'Angin', undercover: 'Badai', category: 'Umum' },
  { civilian: 'Gempa', undercover: 'Tsunami', category: 'Umum' },
  { civilian: 'Bendera', undercover: 'Pita', category: 'Umum' },
  { civilian: 'Liburan', undercover: 'Cuti', category: 'Umum' },
];
