import type { WordPair } from "./types";

export const WORD_PAIRS: WordPair[] = [
  { civilian: "Air Putih", undercover: "Air Dingin", category: "Minuman" },
  { civilian: "Es Teh", undercover: "Teh Hangat", category: "Minuman" },
  { civilian: "Es Jeruk", undercover: "Jus Jeruk", category: "Minuman" },
  { civilian: "Kopi Hitam", undercover: "Kopi Susu", category: "Minuman" },
  { civilian: "Susu Putih", undercover: "Susu Cokelat", category: "Minuman" },
  { civilian: "Jus Mangga", undercover: "Jus Alpukat", category: "Minuman" },
  { civilian: "Soda", undercover: "Cola", category: "Minuman" },
  { civilian: "Teh Botol", undercover: "Teh Kotak", category: "Minuman" },
  { civilian: "Air Kelapa", undercover: "Es Kelapa", category: "Minuman" },
  { civilian: "Cokelat Panas", undercover: "Susu Panas", category: "Minuman" },
  { civilian: "Lemon Tea", undercover: "Lemonade", category: "Minuman" },
  { civilian: "Jamu", undercover: "Wedang Jahe", category: "Minuman" },
  { civilian: "Milkshake", undercover: "Smoothie", category: "Minuman" },
  { civilian: "Boba", undercover: "Thai Tea", category: "Minuman" },
  { civilian: "Sirup", undercover: "Es Buah", category: "Minuman" },

  { civilian: "Nasi Putih", undercover: "Nasi Kuning", category: "Makanan" },
  { civilian: "Mie Goreng", undercover: "Mie Rebus", category: "Makanan" },
  { civilian: "Ayam Goreng", undercover: "Ayam Bakar", category: "Makanan" },
  { civilian: "Ikan Goreng", undercover: "Ikan Bakar", category: "Makanan" },
  { civilian: "Telur Dadar", undercover: "Telur Ceplok", category: "Makanan" },
  { civilian: "Roti Tawar", undercover: "Roti Bakar", category: "Makanan" },
  { civilian: "Kentang Goreng", undercover: "Singkong Goreng", category: "Makanan" },
  { civilian: "Soto Ayam", undercover: "Sop Ayam", category: "Makanan" },
  { civilian: "Bubur Ayam", undercover: "Nasi Tim", category: "Makanan" },
  { civilian: "Bakwan", undercover: "Perkedel", category: "Makanan" },
  { civilian: "Keripik", undercover: "Kerupuk", category: "Makanan" },
  { civilian: "Donat", undercover: "Kue Bolu", category: "Makanan" },
  { civilian: "Pisang Goreng", undercover: "Ubi Goreng", category: "Makanan" },
  { civilian: "Sambal", undercover: "Saus", category: "Makanan" },
  { civilian: "Es Krim", undercover: "Puding", category: "Makanan" },

  { civilian: "Kucing", undercover: "Anjing", category: "Hewan" },
  { civilian: "Ayam", undercover: "Bebek", category: "Hewan" },
  { civilian: "Sapi", undercover: "Kambing", category: "Hewan" },
  { civilian: "Kuda", undercover: "Keledai", category: "Hewan" },
  { civilian: "Ikan", undercover: "Udang", category: "Hewan" },
  { civilian: "Burung", undercover: "Kelelawar", category: "Hewan" },
  { civilian: "Kelinci", undercover: "Hamster", category: "Hewan" },
  { civilian: "Semut", undercover: "Lebah", category: "Hewan" },
  { civilian: "Kupu-Kupu", undercover: "Capung", category: "Hewan" },
  { civilian: "Katak", undercover: "Kodok", category: "Hewan" },
  { civilian: "Kura-Kura", undercover: "Penyu", category: "Hewan" },
  { civilian: "Harimau", undercover: "Singa", category: "Hewan" },
  { civilian: "Gajah", undercover: "Badak", category: "Hewan" },
  { civilian: "Ular", undercover: "Cacing", category: "Hewan" },
  { civilian: "Monyet", undercover: "Gorila", category: "Hewan" },

  { civilian: "Rumah", undercover: "Apartemen", category: "Tempat" },
  { civilian: "Sekolah", undercover: "Kampus", category: "Tempat" },
  { civilian: "Pasar", undercover: "Toko", category: "Tempat" },
  { civilian: "Warung", undercover: "Restoran", category: "Tempat" },
  { civilian: "Pantai", undercover: "Kolam Renang", category: "Tempat" },
  { civilian: "Gunung", undercover: "Bukit", category: "Tempat" },
  { civilian: "Stasiun", undercover: "Terminal", category: "Tempat" },
  { civilian: "Bandara", undercover: "Pelabuhan", category: "Tempat" },
  { civilian: "Rumah Sakit", undercover: "Klinik", category: "Tempat" },
  { civilian: "Taman", undercover: "Lapangan", category: "Tempat" },
  { civilian: "Bioskop", undercover: "Teater", category: "Tempat" },
  { civilian: "Perpustakaan", undercover: "Toko Buku", category: "Tempat" },
  { civilian: "Masjid", undercover: "Musala", category: "Tempat" },
  { civilian: "Kantor", undercover: "Pabrik", category: "Tempat" },
  { civilian: "Hotel", undercover: "Vila", category: "Tempat" },

  { civilian: "Guru", undercover: "Dosen", category: "Profesi" },
  { civilian: "Dokter", undercover: "Perawat", category: "Profesi" },
  { civilian: "Polisi", undercover: "Satpam", category: "Profesi" },
  { civilian: "Koki", undercover: "Penjual Makanan", category: "Profesi" },
  { civilian: "Sopir", undercover: "Ojek", category: "Profesi" },
  { civilian: "Petani", undercover: "Tukang Kebun", category: "Profesi" },
  { civilian: "Nelayan", undercover: "Pelaut", category: "Profesi" },
  { civilian: "Kasir", undercover: "Penjaga Toko", category: "Profesi" },
  { civilian: "Tukang Cukur", undercover: "Penata Rambut", category: "Profesi" },
  { civilian: "Montir", undercover: "Mekanik", category: "Profesi" },
  { civilian: "Penyanyi", undercover: "Pemain Musik", category: "Profesi" },
  { civilian: "Pelukis", undercover: "Desainer", category: "Profesi" },
  { civilian: "Penulis", undercover: "Wartawan", category: "Profesi" },
  { civilian: "Pilot", undercover: "Pramugari", category: "Profesi" },
  { civilian: "Pemadam", undercover: "Penyelamat", category: "Profesi" },

  { civilian: "Meja", undercover: "Kursi", category: "Objek" },
  { civilian: "Buku", undercover: "Majalah", category: "Objek" },
  { civilian: "Pulpen", undercover: "Pensil", category: "Objek" },
  { civilian: "Tas", undercover: "Koper", category: "Objek" },
  { civilian: "Sepatu", undercover: "Sandal", category: "Objek" },
  { civilian: "Baju", undercover: "Jaket", category: "Objek" },
  { civilian: "Topi", undercover: "Helm", category: "Objek" },
  { civilian: "Piring", undercover: "Mangkuk", category: "Objek" },
  { civilian: "Sendok", undercover: "Garpu", category: "Objek" },
  { civilian: "Gelas", undercover: "Botol", category: "Objek" },
  { civilian: "Kompor", undercover: "Oven", category: "Objek" },
  { civilian: "Kipas", undercover: "AC", category: "Objek" },
  { civilian: "Laptop", undercover: "Tablet", category: "Objek" },
  { civilian: "Televisi", undercover: "Proyektor", category: "Objek" },
  { civilian: "Payung", undercover: "Jas Hujan", category: "Objek" },

  { civilian: "Sepak Bola", undercover: "Futsal", category: "Olahraga" },
  { civilian: "Basket", undercover: "Voli", category: "Olahraga" },
  { civilian: "Bulu Tangkis", undercover: "Tenis", category: "Olahraga" },
  { civilian: "Renang", undercover: "Menyelam", category: "Olahraga" },
  { civilian: "Lari", undercover: "Jalan Cepat", category: "Olahraga" },
  { civilian: "Bersepeda", undercover: "Skuter", category: "Olahraga" },
  { civilian: "Tinju", undercover: "Gulat", category: "Olahraga" },
  { civilian: "Karate", undercover: "Taekwondo", category: "Olahraga" },
  { civilian: "Panahan", undercover: "Menembak", category: "Olahraga" },
  { civilian: "Senam", undercover: "Yoga", category: "Olahraga" },
  { civilian: "Catur", undercover: "Dam", category: "Olahraga" },
  { civilian: "Biliar", undercover: "Bowling", category: "Olahraga" },
  { civilian: "Panjat Tebing", undercover: "Mendaki", category: "Olahraga" },
  { civilian: "Kasti", undercover: "Bisbol", category: "Olahraga" },
  { civilian: "Tenis Meja", undercover: "Badminton", category: "Olahraga" },

  { civilian: "Pagi", undercover: "Siang", category: "Umum" },
  { civilian: "Malam", undercover: "Sore", category: "Umum" },
  { civilian: "Panas", undercover: "Hangat", category: "Umum" },
  { civilian: "Dingin", undercover: "Sejuk", category: "Umum" },
  { civilian: "Hujan", undercover: "Gerimis", category: "Umum" },
  { civilian: "Angin", undercover: "Badai", category: "Umum" },
  { civilian: "Lampu", undercover: "Lilin", category: "Umum" },
  { civilian: "Pintu", undercover: "Jendela", category: "Umum" },
  { civilian: "Kunci", undercover: "Gembok", category: "Umum" },
  { civilian: "Uang", undercover: "Kartu", category: "Umum" },
  { civilian: "Hadiah", undercover: "Kado", category: "Umum" },
  { civilian: "Liburan", undercover: "Cuti", category: "Umum" },
  { civilian: "Rapat", undercover: "Diskusi", category: "Umum" },
  { civilian: "Ujian", undercover: "Kuis", category: "Umum" },
  { civilian: "Tidur", undercover: "Istirahat", category: "Umum" },
];
